chore: use oxfmt instead of prettier
close https://github.com/eggjs/egg/issues/5604

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -48,6 +48,9 @@ jobs:
       - name: Run typecheck
         run: pnpm run typecheck
 
+      - name: Run format check
+        run: pnpm run fmtcheck || echo "fmtcheck failed, ignore before it stable"
+
       - name: Run build
         run: pnpm run build
 
